from __future__ import annotations

import argparse
import ast
import os
import shutil
from pathlib import Path


CLEAN_BUILD = True
ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = ROOT / "project"
BUILD_ROOT = PROJECT_ROOT / "build"
DIST_ROOT = PROJECT_ROOT / "dist"
SPEC_ROOT = PROJECT_ROOT / "spec"
SPEC_FILE = SPEC_ROOT / "NetConsole.spec"
ENTRY_FILE = PROJECT_ROOT / "main.py"
RUNTIME_ROOT = BUILD_ROOT / "clean_runtime"

ALLOWED_DATA = [
    ("netconsole", "netconsole"),
    ("data", "data"),
    ("netconsole/ui/icons", "netconsole/ui/icons"),
    ("netconsole/docs/changelog.md", "netconsole/docs/changelog.md"),
]
FORBIDDEN_DATA = [
    (".", "."),
    ("project", "project"),
    ("tests", "tests"),
    ("docs", "docs"),
]
EXCLUDE_DIRS = [
    "tests",
    "docs",
    "project",
    "__pycache__",
    ".git",
    "build",
    "spec",
    "release",
]
EXCLUDE_FILES = {"*.pyc", "*.pyo"}


def scan_import_graph() -> list[str]:
    runtime_modules: set[str] = set()
    sources = [ENTRY_FILE, *(ROOT / "netconsole").rglob("*.py")]
    for source in sources:
        if source != ENTRY_FILE and any(part in EXCLUDE_DIRS for part in source.parts):
            continue
        try:
            tree = ast.parse(source.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "netconsole" or alias.name.startswith("netconsole."):
                        runtime_modules.add(alias.name)
            elif isinstance(node, ast.ImportFrom) and node.module:
                if node.module == "netconsole" or node.module.startswith("netconsole."):
                    runtime_modules.add(node.module)
    return sorted(runtime_modules)


def prepare_runtime() -> None:
    if not CLEAN_BUILD:
        raise RuntimeError("Clean Build Mode is required for release packaging")
    if RUNTIME_ROOT.exists():
        shutil.rmtree(RUNTIME_ROOT)
    RUNTIME_ROOT.mkdir(parents=True)
    _copy_runtime_package(ROOT / "netconsole", RUNTIME_ROOT / "netconsole")
    _copy_changelog()
    (RUNTIME_ROOT / "data").mkdir(parents=True, exist_ok=True)


def write_spec() -> Path:
    SPEC_ROOT.mkdir(parents=True, exist_ok=True)
    runtime_imports = scan_import_graph()
    spec_text = f'''# -*- mode: python ; coding: utf-8 -*-
# Generated by clean_build_spec.py. Do not add project/docs/tests or "." to datas.

CLEAN_BUILD = {CLEAN_BUILD!r}
ALLOWED_DATA = {ALLOWED_DATA!r}
EXCLUDE_DIRS = {EXCLUDE_DIRS!r}
RUNTIME_IMPORTS = {runtime_imports!r}

a = Analysis(
    [{str(ENTRY_FILE)!r}],
    pathex=[{str(ROOT)!r}],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['tests', 'docs', 'project', '__pycache__'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NetConsole',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version={str(PROJECT_ROOT / "version_info.txt")!r},
    icon=[{str(ROOT / "netconsole" / "ui" / "icons" / "love.ico")!r}],
    contents_directory='_internal',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NetConsole',
)
'''
    SPEC_FILE.write_text(spec_text, encoding="utf-8")
    return SPEC_FILE


def finalize_dist() -> None:
    app_dist = DIST_ROOT / "NetConsole"
    if not app_dist.exists():
        raise FileNotFoundError(f"missing PyInstaller output: {app_dist}")
    _replace_tree(RUNTIME_ROOT / "netconsole", app_dist / "netconsole")
    _replace_tree(RUNTIME_ROOT / "data", app_dist / "data")
    validate_dist()


def validate_dist() -> None:
    app_dist = DIST_ROOT / "NetConsole"
    allowed_root = {"NetConsole.exe", "_internal", "netconsole", "data"}
    if not app_dist.exists():
        raise FileNotFoundError(f"missing dist directory: {app_dist}")
    unexpected = [path.name for path in app_dist.iterdir() if path.name not in allowed_root]
    if unexpected:
        raise RuntimeError(f"unexpected dist root items: {unexpected}")
    required = ["NetConsole.exe", "_internal", "netconsole"]
    missing = [name for name in required if not (app_dist / name).exists()]
    if missing:
        raise RuntimeError(f"missing required dist items: {missing}")
    forbidden_relative = [
        "docs",
        "tests",
        "project",
        "build",
        "spec",
        "_internal/netconsole",
        "netconsole/tests",
        "netconsole/project",
        "netconsole/__pycache__",
    ]
    for relative in forbidden_relative:
        if (app_dist / relative).exists():
            raise RuntimeError(f"forbidden dist item exists: {relative}")
    changelog = app_dist / "netconsole" / "docs" / "changelog.md"
    if not changelog.exists():
        raise RuntimeError("runtime changelog is missing")
    icon = app_dist / "netconsole" / "ui" / "icons" / "love.ico"
    if not icon.exists():
        raise RuntimeError("runtime icon is missing")


def _copy_runtime_package(source: Path, destination: Path) -> None:
    def ignore(directory: str, names: list[str]) -> set[str]:
        ignored: set[str] = set()
        for name in names:
            path = Path(directory) / name
            if path.is_dir() and name in EXCLUDE_DIRS:
                ignored.add(name)
            if name.endswith((".pyc", ".pyo")):
                ignored.add(name)
        return ignored

    shutil.copytree(source, destination, ignore=ignore)


def _copy_changelog() -> None:
    source = ROOT / "netconsole" / "docs" / "changelog.md"
    if not source.exists():
        return
    destination = RUNTIME_ROOT / "netconsole" / "docs" / "changelog.md"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def _replace_tree(source: Path, destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate and validate NetConsole clean PyInstaller build")
    parser.add_argument("--prepare", action="store_true", help="stage runtime-only files")
    parser.add_argument("--write-spec", action="store_true", help="write project/spec/NetConsole.spec")
    parser.add_argument("--finalize", action="store_true", help="copy runtime subset into dist and validate")
    parser.add_argument("--validate", action="store_true", help="validate existing dist output")
    args = parser.parse_args()

    if args.prepare:
        prepare_runtime()
    if args.write_spec:
        write_spec()
    if args.finalize:
        finalize_dist()
    if args.validate:
        validate_dist()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
