const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
let targets = [];
let rawExpanded = false;
let rawAuto = false;
let rawTab = 'mesh_link';
const token = () => sessionStorage.getItem('agentToken') || '';
const zhStatus = {created:'已创建',starting:'启动中',running:'采集中',stopping:'停止中',stopped:'已停止',completed:'已完成',completed_with_warnings:'已完成，有告警',stopped_with_warnings:'已停止，有告警',failed:'失败',cancelled:'已取消',idle:'未启动'};
const zhTask = {mr_realtime_collect:'车载 MR 在线收集',iperf_server:'iPerf 服务端',iperf_client:'iPerf 客户端',ping_probe:'连通性探测',fping:'高频 Ping'};
function statusText(v){return zhStatus[String(v||'').toLowerCase()]||v||'未启动'}
function statusClass(v){return 'status-'+String(v||'idle').toLowerCase().replaceAll('_','-')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){return Number(v)||0}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function notice(message,error=false){const n=$('#notice');n.textContent=message;n.className=error?'error':'';n.style.display='block';clearTimeout(n.timer);n.timer=setTimeout(()=>n.style.display='none',5000)}
async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers['X-Agent-Token']=token();if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const response=await fetch('/api/v1/'+path,{...options,headers});const value=await response.json().catch(()=>({ok:false,error:{message:'响应不是有效 JSON'}}));if(!response.ok||!value.ok){const detail=[value.error?.message,value.error?.hint,value.error?.path].filter(Boolean).join('\n');throw new Error(detail||`HTTP ${response.status}`)}return value.data}

async function loadStatus(){const s=await api('status');const labels={agent_name:'Agent',version:'版本',os:'系统',arch:'架构',listen:'监听',uptime:'运行时间',current_tasks:'运行任务',task_count:'任务总数',package_count:'采集包'};$('#status-cards').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="card"><b>${l}</b>${esc(s[k])}</div>`).join('');const p=s.power||{};$('#power-card').innerHTML=`<span class="state ${statusClass(p.active?(p.display_required?'running':'completed'):'idle')}">${p.supported?(p.active?(p.display_required?'防休眠并保持屏幕':'防止系统休眠'):'未启用'):'当前平台不支持'}</span><span>模式：${esc(p.mode||'off')}　最近原因：${esc(p.last_reason||'-')}　${p.last_error?`错误：${esc(p.last_error)}`:''}</span>`}
async function loadTools(){const data=await api('tools/status');const labels={mr_collector:'MR 采集器',iperf3:'iperf3',fping:'fping'};$('#tools-cards').innerHTML=Object.entries(labels).map(([key,label])=>{const t=data.tools?.[key]||{};const state=t.ready?'已找到':t.exists?'有告警':'未找到';const klass=t.ready?'tool-ok':t.exists?'tool-warning':'tool-missing';const missing=(t.required_files||[]).filter(x=>!x.exists).map(x=>x.name).join(', ');return `<div class="card tool-card ${klass}"><b>${label}：${state}</b><div class="tool-path">${esc(t.path)}</div>${t.version?`<div>${esc(t.version)}</div>`:''}${missing?`<div>缺失：${esc(missing)}</div>`:''}${t.warning?`<div>${esc(t.warning)}</div>`:''}</div>`}).join('');return data.tools||{}}
async function loadConfig(){const config=await api('config');$('#config-output').textContent=JSON.stringify(config,null,2)}

function fillMRTargetSelectors(){const mr=targets.filter(t=>t.type==='mr');$('#mr-targets').innerHTML=mr.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${esc(t.host)})</option>`).join('');const all='<option value="">-</option>'+targets.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${esc(t.host)})</option>`).join('');$('#fping1-device').innerHTML=all;$('#fping2-device').innerHTML=all;syncPing1FromMR()}
function syncPing1FromMR(){const id=$('#mr-targets')?.value;const target=targets.find(t=>t.id===id);if(!target)return;$('#fping1-device').value=target.id;$('#fping1-host').value=target.host||''}
async function loadTargets(){const data=await api('targets');targets=data.targets||[];$('#targets-body').innerHTML=targets.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.name)}</td><td>${esc(t.type)}</td><td>${esc(t.host)}:${esc(t.port)}</td><td>${esc(t.protocol)}</td><td>${esc(t.remark)}</td><td><button data-edit-target="${esc(t.id)}">编辑</button> <button data-test-target="${esc(t.id)}">测试</button> <button data-delete-target="${esc(t.id)}">删除</button></td></tr>`).join('');fillMRTargetSelectors()}
async function loadTasks(){const items=await api('tasks');$('#tasks-body').innerHTML=items.map(t=>`<tr><td>${esc(t.task_id)}</td><td>${esc(zhTask[t.task_type]||t.task_type)}</td><td><span class="state ${statusClass(t.status)}">${esc(statusText(t.status))}</span></td><td>${esc(t.start_time)}</td><td>${esc(t.end_time)}</td><td>${t.package_download_url?'有':'-'}</td><td><button data-log-task="${esc(t.task_id)}">日志</button> ${['running','stopping'].includes(t.status)?`<button data-stop-task="${esc(t.task_id)}">停止</button>`:''}</td></tr>`).join('')}
async function loadPackages(){const items=await api('packages');$('#packages-body').innerHTML=items.map(p=>`<tr><td>${esc(p.package_id)}</td><td>${esc(zhTask[p.task_type]||p.task_type)}</td><td>${esc(p.end_time)}</td><td>${(p.size/1024).toFixed(1)} KiB</td><td><button data-download-package="${esc(p.package_id)}">下载</button> <button data-delete-package="${esc(p.package_id)}">删除</button></td></tr>`).join('')}

async function loadMRStatus(){const s=await api('mr/collect/status');const running=['running','starting','stopping'].includes(String(s.status||'').toLowerCase());$('#mr-status-card').className=`status-panel ${statusClass(s.status)}`;$('#mr-status-card').innerHTML=`<div class="status-line"><span class="state ${statusClass(s.status)}">${esc(statusText(s.status))}</span><span>任务：${esc(s.task_id||'-')}</span><span>开始：${esc(s.start_time||'-')}</span><span>采集包：${s.package_download_url?'可下载':'未生成'}</span></div>${s.error_message?`<div class="error-text">${esc(s.error_message)}</div>`:''}`;return {status:s,running}}
function liveCard(label,value){return `<div class="card"><b>${esc(label)}</b>${esc(value??'-')}</div>`}
async function loadMRLive(){const data=await api('mr/collect/live');if(!data.running){$('#mr-live').innerHTML=liveCard('实时状态','当前没有运行中的车载 MR 在线收集任务');return data}const link=data.link_status||{};const fp=data.fping_status||{};const ip=data.iperf_status||{};const summary=fp.summary||{};$('#mr-live').innerHTML=[liveCard('主链路 AP',link.peer_name||'暂无实时链路数据'),liveCard('Peer MAC',link.peer_mac||'暂无实时链路数据'),liveCard('RSSI',link.rssi??'暂无实时链路数据'),liveCard('链路状态',link.link_state||'暂无实时链路数据'),liveCard('站点/区间',[link.display_context?.station,link.display_context?.section].filter(Boolean).join(' / ')||'暂无'),liveCard('fping 当前延时',summary.targets?Object.values(summary.targets).map(x=>x.avg_latency_ms??'-').join(' / ')+' ms':'暂无'),liveCard('fping 丢包率',summary.loss_percent==null?'-':summary.loss_percent+'%'),liveCard('iPerf 当前速率',ip.bitrate_mbps==null?'-':ip.bitrate_mbps+' Mbps'),liveCard('collector 状态',Object.entries(data.mr_status?.collectors||{}).map(([k,v])=>`${k}:${statusText(v.status)}`).join('；')||'暂无')].join('');return data}
async function loadMRLog(){const status=await api('mr/collect/status');if(!status.task_id){$('#mr-log').textContent='暂无日志';return}const data=await api(`tasks/${encodeURIComponent(status.task_id)}/logs?tail=300`);$('#mr-log').textContent=(data.lines||[]).join('\n')}
async function loadRawTab(){if(!rawExpanded)return;try{const data=await api(`mr/collect/raw-tail?name=${encodeURIComponent(rawTab)}&tail=${rawTab==='fping_samples'?100:200}`);$('#raw-output').textContent=data.exists?(data.lines||[]).join('\n'):(data.message||'文件不存在或尚未生成')}catch(e){notice(e.message,true)}}
async function loadRawSummary(){if(!rawExpanded)return;try{await api('mr/collect/raw-summary')}catch(e){/* 采集刚启动时允许 summary 尚未生成 */}}
async function refresh(name){try{if(name==='status')await Promise.all([loadStatus(),loadTools()]);if(name==='targets')await loadTargets();if(name==='tasks')await loadTasks();if(name==='packages')await loadPackages();if(name==='config')await loadConfig();if(name==='mr')await Promise.all([loadMRStatus(),loadMRLive(),loadMRLog()])}catch(e){notice(e.message,true)}}

$$('nav button').forEach(button=>button.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));$$('.page').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#page-'+button.dataset.page).classList.add('active');refresh(button.dataset.page)});
$$('[data-refresh]').forEach(button=>button.onclick=()=>refresh(button.dataset.refresh));
$('#save-token').onclick=()=>{sessionStorage.setItem('agentToken',$('#token').value);notice('Token 已保存到当前浏览器会话');refresh('status')};$('#token').value=token();
$('#mr-targets').addEventListener('change',syncPing1FromMR);$('#fping1-device').addEventListener('change',e=>{const t=targets.find(x=>x.id===e.target.value);if(t)$('#fping1-host').value=t.host||''});$('#fping2-device').addEventListener('change',e=>{const t=targets.find(x=>x.id===e.target.value);if(t)document.querySelector('[name=fping2_host]').value=t.host||''});
$('#target-form').onsubmit=async e=>{e.preventDefault();const value=formObject(e.target),editing=e.target.dataset.editing;value.port=num(value.port);try{await api('targets'+(editing?'/'+encodeURIComponent(editing):''),{method:editing?'PUT':'POST',body:JSON.stringify(value)});notice('目标已保存');e.target.reset();delete e.target.dataset.editing;await loadTargets()}catch(err){notice(err.message,true)}};$('#target-reset').onclick=()=>{$('#target-form').reset();delete $('#target-form').dataset.editing};
$('#target-import').onchange=async e=>{try{await api('targets/import',{method:'POST',body:JSON.stringify(JSON.parse(await e.target.files[0].text()))});notice('目标已导入');await loadTargets()}catch(err){notice(err.message,true)}e.target.value=''};$('#target-export').onclick=async()=>{try{const data=await api('targets');downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'targets.json')}catch(e){notice(e.message,true)}};
$('#targets-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.editTarget){const t=targets.find(x=>x.id===b.dataset.editTarget),f=$('#target-form');Object.entries(t).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});f.dataset.editing=t.id;notice('已载入目标，修改后保存')}if(b.dataset.testTarget){await api(`targets/${encodeURIComponent(b.dataset.testTarget)}/test`,{method:'POST'});notice('连接测试成功')}if(b.dataset.deleteTarget&&confirm('确认删除该目标？')){await api(`targets/${encodeURIComponent(b.dataset.deleteTarget)}`,{method:'DELETE'});await loadTargets();notice('目标已删除')}}catch(err){notice(err.message,true)}};

function buildMR(v){const t=targets.find(x=>x.id===v.target_id)||{};return {target_id:v.target_id,remark:v.remark||'',session:{site:v.display_site||'',mr_id:t.id||'',mr_name:t.name||'',device_id:t.id||'',device_name:t.name||''},display_context:{site:v.display_site||'',station:v.display_station||'',section:v.display_section||'',direction:v.display_direction||''},intervals:{mesh_link:num(v.interval_mesh_link),channel_busy:num(v.interval_channel_busy),ap_radio_statistics:num(v.interval_ap_radio_statistics),switch_history:num(v.interval_switch_history),interface_rate:num(v.interval_interface_rate),wireless_status:num(v.interval_wireless_status)},radio:{mesh_link_radio:num(v.radio_mesh_link),channel_busy_radio:num(v.radio_channel_busy),ap_radio_statistics_radio:num(v.radio_ap_radio_statistics),wireless_status_radio:num(v.radio_wireless_status)},items:{terminal_monitor:v.terminal_monitor==='on',mesh_link:v.mesh_link==='on',channel_busy:v.channel_busy==='on',ap_radio_statistics:v.ap_radio_statistics==='on',switch_history:v.switch_history==='on',interface_rate:v.interface_rate==='on',wireless_status:v.wireless_status==='on'},fping:{enabled:v.fping_enabled==='on',template:v.fping_template||'',targets:[{name:'Ping 1',host:v.fping1_host||''},{name:'Ping 2',host:v.fping2_host||''}],packet_size:num(v.fping_packet_size),interval_ms:num(v.fping_interval_ms),timeout_ms:num(v.fping_timeout_ms),loss_alarm_percent:Number(v.fping_loss_alarm_percent)||0.7,latency_alarm_ms:num(v.fping_latency_alarm_ms)},iperf:{enabled:v.iperf_enabled==='on',server_host:v.iperf_server_host||'',server_port:num(v.iperf_server_port),protocol:v.iperf_protocol||'tcp',direction:v.iperf_direction||'upload',parallel:num(v.iperf_parallel),bandwidth_mbps:num(v.iperf_bandwidth_mbps),threshold_mbps:num(v.iperf_threshold_mbps),duration_sec:num(v.iperf_duration_sec),reverse:v.iperf_reverse==='on'},auto_package_on_stop:true}}
async function start(e,path,build,options={}){e.preventDefault();try{const value=build(formObject(e.target));const tools=await loadTools();if(options.iperf&&!tools.iperf3?.ready)throw new Error((tools.iperf3?.warning||'iperf3 不可用')+'\n请将 iperf3.exe 及相关 DLL 放到 tools/windows-x64/iperf3/');if(options.mr&&!tools.mr_collector?.ready)throw new Error((tools.mr_collector?.warning||'MR 采集器不可用')+'\n请将 netconsole-mr-collector.exe 放到 tools/windows-x64/mr_collector/');if(options.mr&&value.fping.enabled&&value.fping.targets.some(x=>String(x.host||'').trim())&&!tools.fping?.ready)throw new Error((tools.fping?.warning||'fping 不可用')+'\n请将 fping.exe 和 cygwin1.dll 放到 tools/windows-x64/fping/');const task=await api(path,{method:'POST',body:JSON.stringify(value)});notice('任务已启动：'+task.task_id);await loadTasks()}catch(err){notice(err.message,true)}}
$('#iperf-server-form').onsubmit=e=>start(e,'iperf/server/start',v=>({bind:v.bind,port:num(v.port),protocol:v.protocol||'tcp',extra_args:[]}),{iperf:true});$('#iperf-client-form').onsubmit=e=>start(e,'iperf/client/start',v=>({server_host:v.server_host,server_port:num(v.server_port),protocol:String(v.protocol||'tcp').toLowerCase(),duration_sec:num(v.duration_sec),parallel:num(v.parallel),bandwidth_mbps:num(v.bandwidth_mbps),reverse:v.reverse==='on',threshold_mbps:num(v.threshold_mbps),extra_args:[]}),{iperf:true});$('#ping-form').onsubmit=e=>start(e,'ping-probe/start',v=>({targets:v.targets.split(/[\s,，]+/).filter(Boolean),tcp_port:num(v.tcp_port),interval_ms:num(v.interval_ms),timeout_ms:num(v.timeout_ms),packet_size:num(v.packet_size),count:num(v.count)}));$('#mr-form').onsubmit=e=>start(e,'mr/collect/start',buildMR,{mr:true});
$$('[data-stop-type]').forEach(button=>button.onclick=async()=>{try{await api(button.dataset.stopType+'/stop',{method:'POST'});notice('已请求停止')}catch(e){notice(e.message,true)}});
$('#mr-package-button').onclick=async()=>{try{const s=await api('mr/collect/status');if(!s.package_download_url)throw new Error('当前 MR 任务还没有可下载采集包');const response=await fetch(s.package_download_url,{headers:token()?{'X-Agent-Token':token()}:{}});if(!response.ok)throw new Error('下载失败');downloadBlob(await response.blob(),(s.package_id||s.task_id)+'.zip')}catch(e){notice(e.message,true)}};
$('#tasks-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.logTask){const data=await api(`tasks/${encodeURIComponent(b.dataset.logTask)}/logs?tail=300`);$('#task-log').textContent=(data.lines||[]).join('\n')}if(b.dataset.stopTask){await api(`tasks/${encodeURIComponent(b.dataset.stopTask)}/stop`,{method:'POST'});notice('已请求停止');await loadTasks()}}catch(err){notice(err.message,true)}};
$('#packages-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.downloadPackage){const response=await fetch(`/api/v1/packages/${encodeURIComponent(b.dataset.downloadPackage)}/download`,{headers:token()?{'X-Agent-Token':token()}:{}});if(!response.ok)throw new Error('下载失败');downloadBlob(await response.blob(),b.dataset.downloadPackage+'.zip')}if(b.dataset.deletePackage&&confirm('确认删除该采集包？')){await api(`packages/${encodeURIComponent(b.dataset.deletePackage)}`,{method:'DELETE'});await loadPackages();notice('采集包已删除')}}catch(err){notice(err.message,true)}};
$('#raw-toggle').onclick=async()=>{rawExpanded=!rawExpanded;$('#raw-panel').hidden=!rawExpanded;$('#raw-toggle').textContent=rawExpanded?'隐藏原始采集':'显示原始采集';$('#raw-refresh').hidden=!rawExpanded;$('#raw-auto').hidden=!rawExpanded;if(rawExpanded)await loadRawTab()};$('#raw-refresh').onclick=loadRawTab;$('#raw-auto').onclick=()=>{rawAuto=!rawAuto;$('#raw-auto').textContent='自动刷新：'+(rawAuto?'开':'关');if(rawAuto)loadRawTab()};$$('[data-raw]').forEach(button=>button.onclick=async()=>{rawTab=button.dataset.raw;$$('[data-raw]').forEach(x=>x.classList.remove('active'));button.classList.add('active');await loadRawTab()});
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
setInterval(async()=>{if($('#page-mr').classList.contains('active')){try{await Promise.all([loadMRStatus(),loadMRLive(),loadMRLog()]);if(rawAuto)await loadRawTab()}catch(e){/* 启动/停止窗口允许短暂失败 */}}},1000);setInterval(()=>{if($('#page-mr').classList.contains('active'))loadRawSummary()},5000);setInterval(()=>{if($('#page-status').classList.contains('active'))refresh('status')},5000);
Promise.all([refresh('status'),refresh('targets')]);
