import { describe, expect, it } from 'vitest'

import source from './DeviceManagementView.vue?raw'
import deviceTypesSource from '../../types/deviceManagement.ts?raw'

describe('Device Management Web view', () => {
  it('fills the route width and gives the device table the remaining window height', () => {
    expect(source).toContain('.device-management { display: flex; width: 100%; height: 100%; max-width: none;')
    expect(source).toContain('.table-card { display: flex; min-height: 0; flex: 1;')
    expect(source).toContain('.device-table-host { display: flex; min-height: 0; flex: 1;')
    expect(source).toContain('height="100%"')
    expect(source).not.toContain('max-width: 1720px')
    expect(source).not.toContain('height="calc(100vh - 380px)"')
  })

  it('covers loading, empty, error and success states', () => {
    expect(source).toContain('v-loading="loading"')
    expect(source).toContain('v-if="isEmpty"')
    expect(source).toContain('v-if="error"')
    expect(source).toContain("'empty' : 'success'")
  })

  it('supports filters, shared full detail presentation and desktop-only explicit credential reveal', () => {
    expect(source).toContain('connection_status')
    expect(source).toContain('group_id')
    expect(source).toContain('device_type')
    expect(source).toContain('DEVICE_TYPE_OPTIONS')
    expect(source).toContain('MR')
    expect(source).toContain('filters.vendor')
    expect(source).toContain('DEVICE_VENDOR_OPTIONS')
    expect(deviceTypesSource).toContain("{ value: 'ZTE', label: '中兴 ZTE' }")
    expect(source).toContain('formatDeviceVendor(row.device_vendor)')
    expect(source).toContain('openDetail(row)')
    expect(source).toContain('detailDeviceUuid.value = item.device_uuid')
    expect(source).not.toContain('getDevice(')
    expect(source).not.toContain('detail.value = await getDevice(item.device_uuid)')
    expect(source).toContain('async function openEdit(deviceUuid = detailDeviceUuid.value)')
    expect(source).toContain('getDeviceEditProfile(deviceUuid, controller.signal)')
    expect(source).toContain('const editingDeviceUuid = ref(\'\')')
    expect(source).toContain('editLoadGeneration')
    expect(source).toContain('editProfileAbortController')
    expect(source).toContain('editingProfileLoading')
    expect(source).toContain('<DeviceDetailPanel')
    expect(source).toContain(':size="detailDrawerWidth"')
    expect(source).toContain('beginDrawerResize')
    expect(source).toContain('handleDrawerResizeKeydown')
    expect(source).toContain('aria-valuenow')
    expect(source).toContain('aria-valuemin')
    expect(source).toContain('aria-valuemax')
    expect(source).toContain('@full-detail="openFullDetail"')
    expect(source).toContain('background: var(--nc-bg-muted)')
    expect(source).toContain('updateDevice(editedUuid, deviceWritePayload())')
    expect(source).toContain('device_uuid: editTargetUuid || undefined')
    expect(source).not.toContain('device_uuid: writeMode.value === \'edit\' ? detailDeviceUuid.value : undefined')
    expect(source).toContain(":type=\"secretVisible.ssh_password ? 'text' : 'password'\"")
    expect(source).toContain('revealDeviceCredential(editingDeviceUuid.value, field)')
    expect(source).toContain('仅本机桌面端可以读取已保存凭据')
    expect(source).toContain('autocomplete="new-password"')
    expect(source).toContain('已配置；留空保留')
    expect(source).toContain('clear_secret_fields')
    expect(source).toContain('清除已保存值')
    expect(source).toContain('startDeviceFormConnectionTest')
    expect(source).toContain('测试表单连接')
    expect(source).toContain("isFeatureEnabled('web.device_form_connection_test')")
    expect(source).toContain('writeConnectionDisabledReason')
    expect(source).toContain('getDeviceConnectionTest')
    expect(source).toContain('打开任务窗口')
    expect(source).not.toContain('等待共享 Job Runtime 非序列化 bootstrap 接入')
  })

  it('submits background connection tests to the public task center', () => {
    expect(source).toContain('startBatchConnectionTests')
    expect(source).toContain('任务已提交，但')
    expect(source).toContain('任务状态刷新失败')
    expect(source).toContain('任务窗口打开失败')
    expect(source).toContain('openTaskWindow(publicTask || null, task.task_id, false)')
  })

  it('uses a dedicated batch refresh confirmation and loading state', () => {
    expect(source).toContain('batchRefreshSubmitting')
    expect(source).toContain('batchRefreshTargetCount')
    expect(source).toContain(':loading="batchRefreshSubmitting"')
    expect(source).toContain('正在提交 {{ batchRefreshTargetCount }} 台设备详情更新任务...')
    expect(source).toContain('确定更新选中的')
    expect(source).toContain('startBatchRefreshDetails(targets)')
  })

  it('matches current-page selection and row operations', () => {
    expect(source).toContain('function clearSelection()')
    expect(source).toContain('function invertSelection()')
    expect(source).toContain('toggleRowSelection')
    expect(source).toContain('@row-dblclick="openDetail"')
    expect(source).toContain('复制设备')
    expect(source).toContain('copyDeviceInfo')
  })

  it('uses the unified table contract for the device and OmniPeek tables', () => {
    expect(source).toContain('table-id="device-list"')
    expect(source).toContain('table-id="device-omnipeek-export"')
    expect(source).toContain(':columns="deviceColumns"')
    expect(source).toContain(':columns="omniPeekColumns"')
    expect(source).not.toContain('<el-table')
    expect(source).not.toContain('<el-table-column')
    expect(source).toContain("key: 'name', label: '名称', valueType: 'name', fixed: 'left', stretch: 'priority'")
    expect(source).toContain("key: 'station', label: '站点', valueType: 'text', stretch: 'priority'")
    expect(source).toContain("key: 'updated_at', label: '更新时间', valueType: 'datetime', stretch: 'none'")
    expect(source).toContain("key: 'actions', label: '操作', valueType: 'actions'")
    expect(source).toContain("stretch: 'none'")
  })

  it('uses safe file upload and controlled server exports', () => {
    expect(source).toContain('type="file"')
    expect(source).toContain('previewDeviceImport(importFile.value)')
    expect(source).toContain('importPreview.total_rows')
    expect(source).toContain('importPreview.valid_rows')
    expect(source).toContain('importPreview.vendor_summary.ZTE')
    expect(source).toContain('table-id="device-import-errors"')
    expect(source).not.toContain('Invalid device_vendor')
    expect(source).toContain('importDuplicateStrategy')
    expect(source).toContain("value=\"reject\"")
    expect(source).toContain("value=\"skip\"")
    expect(source).toContain("value=\"create_new\"")
    expect(source).not.toContain('importPath')
    expect(source).not.toContain('output_path')
    expect(source).not.toContain('output_dir')
    expect(source).not.toContain('template_ini')
    expect(source).not.toContain('file_path')
    expect(source).toContain('startOmniPeekPreview')
    expect(source).toContain('getOmniPeekPreview')
    expect(source).toContain('selected_item_keys')
    expect(source).toContain('force_export_keys')
    expect(source).toContain('startSecureCrtExportWithTemplate')
    expect(source).toContain('accept=".ini"')
    expect(source).toContain('stopOmniPeekPreview')
    expect(source).toContain('设备表格导出完成，共 ${task.row_count ?? 0} 台设备')
    expect(source).not.toContain('handledInteractiveExportTaskIds')
    expect(source).toContain('localSaveStatuses')
    expect(source).toContain("'local_save_prompting'")
    expect(source).toContain("'local_save_cancelled'")
    expect(source).toContain("'local_save_failed'")
    expect(source).toContain('saveDeviceCsvArtifact')
    expect(source).toContain('expectedSizeBytes: task.size_bytes')
    expect(source).toContain('expectedSha256: task.sha256')
    expect(source).toContain('设备表格已生成，但尚未保存到本地。')
    expect(source).toContain('openWindow = true')
    expect(source).toContain('Date.now() + 120_000')
    for (const featureId of [
      'web.device_management_write',
      'web.device_management_collect',
      'web.device_management_import',
      'web.device_management_export',
      'web.device_management_desktop',
    ]) {
      expect(source).toContain(`isFeatureEnabled('${featureId}')`)
    }
  })

  it('statically guards against a page-private task system and path capabilities', () => {
    expect(source).not.toContain('sessionStorage')
    expect(source).not.toContain('taskStorageKey')
    expect(source).not.toContain('trackedTasks')
    expect(source).not.toContain('refreshTrackedTasks')
    expect(source).not.toContain('cancelDeviceTask')
    expect(source).toContain('useTaskStore')
    expect(source).toContain('taskStore.refresh()')
    expect(source).toContain('taskStore.acquirePolling(pollingConsumer)')
    expect(source).toContain('taskStore.releasePolling(pollingConsumer)')
    expect(source).toContain('openTaskWindow')
    expect(source).toContain('downloadBackendResource')
    expect(source).toContain('result.capabilityId')
    expect(source).not.toContain('savedPath')
    expect(source).toContain('getPlatformAdapter().openPath(savedArtifactCapability.value)')
    expect(source).toContain('getPlatformAdapter().showItemInFolder(savedArtifactCapability.value)')
    expect(source).not.toContain('window.location.assign')
  })

  it('builds edit values and launches only configured desktop terminals', () => {
    expect(source).toContain('function currentDeviceWriteValues()')
    expect(source).toContain('Object.assign(writeForm, values)')
    expect(source).toContain('launchExternalTerminals')
    expect(source).toContain('issueExternalTerminalConfirmation')
    expect(source).toContain('getExternalTerminalSettings')
    expect(source).toContain('getPlatformAdapter().selectFile')
    expect(source).toContain("terminalSettings[`${terminalType}_path`] = path")
    expect(source).toContain('外部终端配置仅在 Electron Desktop 中可用')
    expect(source).toContain('@closed="closeWriteDialog"')
    expect(source).not.toContain('等待 Desktop Bridge 执行')
  })
})
