from __future__ import annotations

from netconsole.models.device import Device
from netconsole.repositories.device_repository import DeviceRepository


DEMO_DEVICES = (
    Device(
        name="H3C SW-SSH-SNMPv2c",
        sysname="DEMO-H3C-SW01",
        station="控制中心",
        device_vendor="H3C",
        device_type="SW",
        ip_address="10.10.1.1",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        auth_mode="local",
        username="admin",
        password="admin123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="public",
        snmp_rw_community="private",
        tags="H3C,SSH,SNMPv2c",
        remark="H3C SW with SSH and SNMPv2c.",
    ),
    Device(
        name="H3C FIT-AP-Telnet-SNMPv2c",
        sysname="DEMO-FIT-AP01",
        station="轨旁区间",
        device_vendor="H3C",
        device_type="FIT-AP",
        ip_address="10.10.2.21",
        ssh_enabled=0,
        ssh_port=22,
        telnet_enabled=1,
        telnet_port=23,
        auth_mode="local",
        username="apadmin",
        password="ap123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="ap_public",
        tags="H3C,Telnet,FIT-AP",
        remark="H3C FIT-AP with Telnet and SNMPv2c.",
    ),
    Device(
        name="H3C AC-SSH-Telnet-SNMP-All",
        sysname="DEMO-H3C-AC01",
        station="车辆段无线机房",
        device_vendor="H3C",
        device_type="AC",
        ip_address="10.10.3.10",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=1,
        telnet_port=23,
        auth_mode="local",
        username="wlan",
        password="wlan123",
        snmp_v1_enabled=1,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=1,
        snmp_port=161,
        snmp_ro_community="ac_public",
        snmpv3_security_level="noAuthNoPriv",
        tags="H3C,AC,SNMPv1,SNMPv2c,SNMPv3",
        remark="H3C AC with SSH, Telnet, and all SNMP versions enabled.",
    ),
    Device(
        name="Huawei SW-SSH",
        sysname="DEMO-HW-SW01",
        station="人民广场站",
        device_vendor="Huawei",
        device_type="SW",
        ip_address="10.10.4.1",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        auth_mode="local",
        username="huawei",
        password="huawei123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="hw_public",
        tags="Huawei,SSH",
        remark="Huawei SW with SSH.",
    ),
    Device(
        name="Ruijie SW-SSH",
        sysname="DEMO-RJ-SW01",
        station="体育中心站",
        device_vendor="Ruijie",
        device_type="SW",
        ip_address="10.10.5.1",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        auth_mode="local",
        username="ruijie",
        password="ruijie123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="rj_public",
        tags="Ruijie,SSH",
        remark="Ruijie SW with SSH.",
    ),
    Device(
        name="H3C FW-SSH-SNMPv3-AuthPriv",
        sysname="DEMO-H3C-FW01",
        station="控制中心安全区",
        device_vendor="H3C",
        device_type="FW",
        ip_address="10.10.6.254",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        auth_mode="local",
        username="secadmin",
        password="fw123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=0,
        snmp_v3_enabled=1,
        snmp_port=161,
        snmpv3_security_level="AuthPriv",
        snmpv3_auth_protocol="SHA",
        snmpv3_auth_password="auth123456",
        snmpv3_priv_protocol="AES128",
        snmpv3_priv_password="priv123456",
        tags="H3C,FW,SNMPv3",
        remark="H3C FW with SSH and SNMPv3 AuthPriv.",
    ),
)


def insert_demo_devices(repository: DeviceRepository) -> int:
    for device in DEMO_DEVICES:
        repository.create(device)
    return len(DEMO_DEVICES)
