from __future__ import annotations

from netconsole.models.device import Device
from netconsole.repositories.device_repository import DeviceRepository


DEMO_DEVICES = (
    Device(
        name="Huawei SW-SSH-Only",
        sysname="DEMO-HW-SW01",
        station="人民广场站",
        device_vendor="Huawei",
        device_type="SW",
        ip_address="10.10.1.1",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        ssh_username="huawei",
        ssh_password="huawei123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="hw_public",
        remark="SSH only with username and password.",
    ),
    Device(
        name="Ruijie SW-Telnet-Password",
        sysname="DEMO-RJ-SW01",
        station="体育中心站",
        device_vendor="Ruijie",
        device_type="SW",
        ip_address="10.10.2.1",
        ssh_enabled=0,
        ssh_port=22,
        telnet_enabled=1,
        telnet_port=23,
        telnet_username="",
        telnet_password="ruijie123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="rj_public",
        remark="Telnet only with password and blank username.",
    ),
    Device(
        name="H3C SW-Same-SSH-Telnet",
        sysname="DEMO-H3C-SW01",
        station="控制中心",
        device_vendor="H3C",
        device_type="SW",
        ip_address="10.10.3.1",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=1,
        telnet_port=23,
        ssh_username="admin",
        ssh_password="admin123",
        telnet_username="admin",
        telnet_password="admin123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=0,
        snmp_port=161,
        snmp_ro_community="public",
        snmp_rw_community="private",
        remark="SSH and Telnet use the same credentials.",
    ),
    Device(
        name="H3C AC-Different-SSH-Telnet",
        sysname="DEMO-H3C-AC01",
        station="无线机房",
        device_vendor="H3C",
        device_type="AC",
        ip_address="10.10.4.10",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=1,
        telnet_port=23,
        ssh_username="sshadmin",
        ssh_password="ssh123",
        telnet_username="teladmin",
        telnet_password="tel123",
        snmp_v1_enabled=1,
        snmp_v2c_enabled=1,
        snmp_v3_enabled=1,
        snmp_port=161,
        snmp_ro_community="ac_public",
        snmpv3_security_level="noAuthNoPriv",
        remark="SSH and Telnet use different credentials.",
    ),
    Device(
        name="H3C FW-SSH-SNMPv3-AuthPriv",
        sysname="DEMO-H3C-FW01",
        station="控制中心安全区",
        device_vendor="H3C",
        device_type="FW",
        ip_address="10.10.5.254",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        ssh_username="secadmin",
        ssh_password="fw123",
        snmp_v1_enabled=0,
        snmp_v2c_enabled=0,
        snmp_v3_enabled=1,
        snmp_port=161,
        snmpv3_security_level="AuthPriv",
        snmpv3_auth_protocol="SHA",
        snmpv3_auth_password="auth123456",
        snmpv3_priv_protocol="AES128",
        snmpv3_priv_password="priv123456",
        remark="SNMPv3 AuthPriv example.",
    ),
    Device(
        name="AC",
        station="Demo",
        device_vendor="H3C",
        device_type="AC",
        ip_address="10.0.0.51",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        ssh_username="admin",
        ssh_password="Admin@123",
        remark="模拟器设备，用于 demo 环境测试",
    ),
    Device(
        name="SW01",
        station="Demo",
        device_vendor="H3C",
        device_type="SW",
        ip_address="10.0.0.52",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        ssh_username="admin",
        ssh_password="Admin@123",
        remark="模拟器设备，用于 demo 环境测试",
    ),
    Device(
        name="SW02",
        station="Demo",
        device_vendor="H3C",
        device_type="SW",
        ip_address="10.0.0.53",
        ssh_enabled=1,
        ssh_port=22,
        telnet_enabled=0,
        telnet_port=23,
        ssh_username="admin",
        ssh_password="Admin@123",
        remark="模拟器设备，用于 demo 环境测试",
    ),
)


def insert_demo_devices(repository: DeviceRepository) -> int:
    for device in DEMO_DEVICES:
        repository.create(device)
    return len(DEMO_DEVICES)
