import { describe, expect, it } from 'vitest'

import source from './DeviceManagementView.vue?raw'
import deviceTypesSource from '../../types/deviceManagement.ts?raw'
import coordinatorSource from '../../composables/useUserSelectedExport.ts?raw'

describe('Device Management Web view', () => {
  it('fills the route width and gives the device table the remaining window height', () => {
    expect(source).toContain('.device-management { display: flex; width: 100%; height: 100%; max-width: none;')
    expect(source).toContain('.table-card { display: flex; min-height: 0; flex: 1;')
    expect(source).toContain('.device-table-host { display: flex; min-height: 0; flex: 1;')
    expect(source).toContain('height="100%"')
    expect(source).not.toContain('max-width: 1720px')
    expect(source).not.toContain('height="calc(100vh - 380px)"')
    expect(source).toContain('class="device-detail-drawer"')
    expect(source).toContain(':global(.device-detail-drawer .el-drawer__body) { display: flex; min-height: 0; flex-direction: column; overflow: hidden; }')
  })

  it('covers loading, empty, error and success states', () => {
    expect(source).toContain('v-loading="loading"')
    expect(source).toContain('v-if="isEmpty"')
    expect(source).toContain('v-if="error"')
    expect(source).toContain("'empty' : 'success'")
  })

  it('supports filters, shared full detail presentation and desktop-only explicit credential reveal', () => {
    expect(source).toContain('connection_status')
    expect(source).toContain('group_id')
    expect(source).toContain('device_type')
    expect(source).toContain('DEVICE_TYPE_OPTIONS')
    expect(source).toContain('MR')
    expect(source).toContain('filters.vendor')
    expect(source).toContain('DEVICE_VENDOR_OPTIONS')
    expect(deviceTypesSource).toContain("{ value: 'ZTE', label: '中兴 ZTE' }")
    expect(source).toContain('formatDeviceVendor(row.device_vendor)')
    expect(source).toContain('openDetail(row)')
    expect(source).toContain('detailDeviceUuid.value = item.device_uuid')
    expect(source).not.toContain('getDevice(')
    expect(source).not.toContain('detail.value = await getDevice(item.device_uuid)')
    expect(source).toContain('async function openEdit(deviceUuid = detailDeviceUuid.value)')
    expect(source).toContain('getDeviceEditProfile(deviceUuid, controller.signal)')
    expect(source).toContain('const editingDeviceUuid = ref(\'\')')
    expect(source).toContain('editLoadGeneration')
    expect(source).toContain('editProfileAbortController')
    expect(source).toContain('editingProfileLoading')
    expect(source).toContain('<DeviceDetailPanel')
    expect(source).toContain(':size="detailDrawerWidth"')
    expect(source).toContain('beginDrawerResize')
    expect(source).toContain('handleDrawerResizeKeydown')
    expect(source).toContain('aria-valuenow')
    expect(source).toContain('aria-valuemin')
    expect(source).toContain('aria-valuemax')
    expect(source).toContain('@full-detail="openFullDetail"')
    expect(source).toContain('background: var(--nc-bg-muted)')
    expect(source).toContain('updateDevice(editedUuid, deviceWritePayload())')
    expect(source).toContain('device_uuid: editTargetUuid || undefined')
    expect(source).not.toContain('device_uuid: writeMode.value === \'edit\' ? detailDeviceUuid.value : undefined')
    expect(source).toContain(":type=\"secretVisible.ssh_password ? 'text' : 'password'\"")
    expect(source).toContain('revealDeviceCredential(editingDeviceUuid.value, field)')
    expect(source).toContain('仅本机桌面端可以读取已保存凭据')
    expect(source).toContain('autocomplete="new-password"')
    expect(source).toContain('已配置；留空保留')
    expect(source).toContain('clear_secret_fields')
    expect(source).toContain('清除已保存值')
    expect(source).toContain('startDeviceFormConnectionTest')
    expect(source).toContain('测试表单连接')
    expect(source).toContain("isFeatureEnabled('capability.devices.form_connection_test')")
    expect(source).toContain('writeConnectionDisabledReason')
    expect(source).toContain('getDeviceConnectionTest')
    expect(source).toContain('打开任务中心')
    expect(source).not.toContain('等待共享 Job Runtime 非序列化 bootstrap 接入')
  })

  it('uses backend default group-priority sorting and preserves explicit sort choices', () => {
    expect(source).toContain("sort_by: 'default'")
    expect(source).toContain('默认排序（分组优先 + 名称自然排序）')
    expect(source).toContain('sort_by: filters.sort_by')
  })

  it('submits background connection tests to the public task center', () => {
    expect(source).toContain('startBatchConnectionTests')
    expect(source).toContain('任务已提交，但')
    expect(source).toContain('任务状态刷新失败')
    expect(source).toContain('任务中心打开失败')
    expect(source).toContain('openTaskWindow(publicTask || null, task.task_id, false)')
  })

  it('uses a dedicated batch refresh confirmation and loading state', () => {
    expect(source).toContain('batchRefreshSubmitting')
    expect(source).toContain('batchRefreshTargetCount')
    expect(source).toContain(':loading="batchRefreshSubmitting"')
    expect(source).toContain('正在更新 0/${batchRefreshTargetCount} 台设备')
    expect(source).toContain('确定更新选中的')
    expect(source).toContain('startBatchRefreshDetails(targets)')
    expect(source).toContain('getBatchRefresh(batchId)')
    expect(source).toContain('await loadDevices(false, true)')
    expect(source).not.toContain('showBatchRefreshNotification')
    expect(source).not.toContain('batch-refresh-details-notification')
    expect(source).toContain('批量更新完成：成功')
  })

  it('matches current-page selection and row operations', () => {
    expect(source).toContain('function clearSelection()')
    expect(source).toContain('function invertSelection()')
    expect(source).toContain('toggleRowSelection')
    expect(source).toContain('@row-dblclick="openDetail"')
    expect(source).toContain('computed<NcDataTableContextMenuItem<DeviceListItem>[]>')
    expect(source).toContain(':context-menu-items="deviceContextMenuItems"')
    expect(source).toContain("{ key: 'detail', label: '详情', action: ({ row }) => openDetail(row) }")
    expect(source).toContain("key: 'duplicate'")
    expect(source).toContain("key: 'copy-current-cell'")
    expect(source).toContain("key: 'copy-device-info'")
    expect(source).toContain("key: 'external-terminal'")
    expect(source).toContain("key: 'delete'")
    expect(source).not.toContain('class="device-context-menu"')
    expect(source).not.toContain('function showContextMenu(')
  })

  it('uses the unified table contract for the device table', () => {
    expect(source).toContain('table-id="device-list"')
    expect(source).toContain(':columns="deviceColumns"')
    expect(source).not.toContain('table-id="device-omnipeek-export"')
    expect(source).not.toContain('<el-table')
    expect(source).not.toContain('<el-table-column')
    expect(source).toContain("key: 'name', label: '名称', valueType: 'name', fixed: 'left', stretch: 'priority'")
    expect(source).toContain("key: 'station', label: '站点', valueType: 'text', stretch: 'priority'")
    expect(source).toContain("key: 'metadata_updated_at', label: '资料更新时间', valueType: 'datetime', stretch: 'none'")
    expect(source).toContain("key: 'last_collected_at', label: '最后采集时间', valueType: 'datetime', stretch: 'none'")
    expect(source).toContain("key: 'actions', label: '操作', valueType: 'actions'")
    expect(source).toContain("stretch: 'none'")
  })

  it('uses safe file upload and controlled server exports', () => {
    expect(source).toContain('type="file"')
    expect(source).toContain('previewDeviceImport(')
    expect(source).toContain('importMatchStrategy.value')
    expect(source).toContain('importWriteMode.value')
    expect(source).toContain('importPreview.total_rows')
    expect(source).toContain('importPreview.valid_rows')
    expect(source).toContain('importPreview.vendor_summary')
    expect(source).toContain('collection_supported_rows')
    expect(source).toContain('table-id="device-import-errors"')
    expect(source).toContain('table-id="device-import-row-results"')
    expect(source).not.toContain('Invalid device_vendor')
    expect(source).toContain('按主 IP 更新（当前局点内唯一）')
    expect(source).toContain('value="SITE_PRIMARY_IP"')
    expect(source).toContain('value="DEVICE_ID"')
    expect(source).toContain('value="DEVICE_NAME"')
    expect(source).toContain('value="UPDATE_ONLY"')
    expect(source).toContain('value="UPSERT"')
    expect(source).toContain('importPreview.has_hard_errors')
    expect(source).toContain('批量更新设备')
    expect(source).not.toContain('value="create_new"')
    expect(source).not.toContain('importPath')
    expect(source).not.toContain('output_path')
    expect(source).not.toContain('output_dir')
    expect(source).not.toContain('template_ini')
    expect(source).not.toContain('file_path')
    expect(source).toContain('startSecureCrtExportWithTemplate')
    expect(source).toContain('accept=".ini"')
    expect(source).toContain('submitExportAfterDestinationSelected')
    expect(source).toContain("'devices.csv'")
    expect(source).toContain("'devices.template'")
    expect(source).toContain("'devices.securecrt'")
    expect(source).toContain("'devices.diagnostics'")
    expect(coordinatorSource).toContain("'task_running'")
    expect(coordinatorSource).toContain("'artifact_ready'")
    expect(coordinatorSource).toContain("'save_failed'")
    expect(coordinatorSource).toContain('getPlatformAdapter()')
    expect(coordinatorSource).toContain('destinationPath: binding.destinationPath')
    expect(source).toContain("export_scope: scope")
    expect(source).toContain("scope === 'selected' ? [...selectedUuids.value] : []")
    expect(coordinatorSource).toContain('expectedSizeBytes: artifact.size_bytes')
    expect(coordinatorSource).toContain('expectedSha256: artifact.sha256!')
    expect(coordinatorSource).toContain('重新选择保存位置')
    expect(source).toContain('openWindow = true')
    for (const featureId of [
      'capability.devices.write',
      'capability.devices.collect',
      'capability.devices.import',
      'capability.devices.export',
      'capability.devices.desktop_actions',
    ]) {
      expect(source).toContain(`isFeatureEnabled('${featureId}')`)
    }
  })

  it('removes only the OmniPeek entry from the device export menu', () => {
    expect(source).toContain('@click="exportCsv(false)">CSV 导出（不含凭据）')
    expect(source).toContain('@click="exportCsv(true)">CSV 导出（含凭据）')
    expect(source).toContain('@click="openSecureCrtExport">SecureCRT 会话')
    expect(source).not.toContain('OmniPeek 名称表')
    expect(source).not.toContain('openOmniPeekExport')
  })

  it('uses the shared task store and persists only task-to-save authorization bindings', () => {
    expect(source).toContain('useUserSelectedExport')
    expect(coordinatorSource).toContain("const STORAGE_KEY = 'netconsole.user-selected-exports.v1'")
    expect(coordinatorSource).toContain('window.sessionStorage.setItem')
    expect(coordinatorSource).toContain('restoreBindings')
  })

  it('statically guards against a page-private task system and path capabilities', () => {
    expect(source).not.toContain('taskStorageKey')
    expect(source).not.toContain('trackedTasks')
    expect(source).not.toContain('refreshTrackedTasks')
    expect(source).not.toContain('cancelDeviceTask')
    expect(source).toContain('useTaskStore')
    expect(source).toContain('taskStore.refresh()')
    expect(source).toContain('taskStore.acquirePolling(pollingConsumer)')
    expect(source).toContain('taskStore.releasePolling(pollingConsumer)')
    expect(source).toContain('openTaskWindow')
    expect(source).toContain('downloadBackendResource')
    expect(source).toContain('showDeviceArtifactNotification')
    expect(source).toContain('device-task-notification')
    expect(source).not.toContain('savedPath')
    expect(source).toContain('getPlatformAdapter().openPath(capabilityId)')
    expect(source).toContain('getPlatformAdapter().showItemInFolder(capabilityId)')
    expect(source).not.toContain('window.location.assign')
  })

  it('builds edit values and launches only configured desktop terminals', () => {
    expect(source).toContain('function currentDeviceWriteValues()')
    expect(source).toContain('Object.assign(writeForm, values)')
    expect(source).toContain('useExternalTerminalLauncher')
    expect(source).toContain('preflightDeviceTerminalTargets')
    expect(source).toContain('launchDeviceTerminalTargets')
    expect(source).toContain('getExternalTerminalSettings')
    expect(source).toContain('getPlatformAdapter().selectFile')
    expect(source).toContain("terminalSettings[`${terminalType}_path`] = path")
    expect(source).toContain('外部终端配置仅在 Electron Desktop 中可用')
    expect(source).toContain('@closed="closeWriteDialog"')
    expect(source).not.toContain('等待 Desktop Bridge 执行')
  })
})
