import { describe, expect, it } from 'vitest'

import { meshArtifactDownloadRequest } from '../../api/meshAnalysis'
import source from './MeshAnalysisView.vue?raw'

describe('Mesh analysis view', () => {
  it('shows persisted results and real import and report actions', () => {
    expect(source).toContain('Mesh 原始日志分析')
    expect(source).toContain('主 / 备链路')
    expect(source).toContain('主链路建链顺序')
    expect(source).toContain('切换事件')
    expect(source).toContain('RSSI 分析')
    expect(source).toContain('空口负载')
    expect(source).not.toContain('Rate（原始值）')
    expect(source).not.toContain('Retry / Error 增量')
    expect(source).not.toContain('异常摘要 (')
    expect(source).not.toContain('MeshRateChart')
    expect(source).not.toContain('MeshCounterDeltaChart')
    expect(source).not.toContain('getMeshRateSeries')
    expect(source).not.toContain('getMeshCounterDeltas')
    expect(source).not.toContain('listMeshAnomalies')
    expect(source).not.toContain('MeshUnavailableChart')
    expect(source).not.toContain('fping / iPerf 对齐')
    expect(source).not.toContain('getMeshAlignment')
    expect(source).toContain('报告与来源')
    expect(source).toContain('<el-pagination')
    expect(source).toContain('peer_radio_mac')
    expect(source).not.toContain('归属来源')
    expect(source).toContain('previewMeshImport')
    expect(source).toContain('applyMeshBundleImport')
    expect(source).toContain('safe_name')
    expect(source).toContain('explicit_confirmation: true')
    expect(source).toContain('createMeshProfile')
    expect(source).toContain('exportMeshAnalysisReport')
    expect(source).toContain('recoverRailTransitTasks')
    expect(source).toContain('rebuildMeshAnalysis')
    expect(source).toContain('mesh_source_rebuild')
    expect(source).not.toMatch(/listVehicleMrs\([^)]*page_size:\s*500/)
    expect(source).toContain('listVehicleMrs({ page, page_size: 200 })')
    expect(source).toContain('loadTab(tab)')
    expect(source).toContain('useAvailablePanelHeight')
    expect(source).not.toContain('height="500"')
    expect(source).not.toContain('min-height:520px')
    expect(source).toContain('.analysis-subtabs :deep(.el-tabs__content){display:none}')
    expect(source).toContain('getMeshActivePathChart')
    expect(source).toContain('getMeshTracksideSignalChart')
    expect(source).toContain('MeshTracksideSignalChartData')
    expect(source).toContain('<MeshTracksideSignalChart')
    expect(source).not.toContain('MeshTracksideSignalChart as MeshTracksideSignalPayload')
    expect(source).toContain('getMeshPeerSegmentChart')
    expect(source).toContain('mesh-analysis-airload.show-switch-lines')
    expect(source).toContain('mesh-analysis-airload.show-switch-points')
    expect(source).toContain(':show-switch-lines="showBusySwitchLines"')
    expect(source).toContain(':show-switch-points="showBusySwitchPoints"')
    expect(source).toContain("openTaskWindow({ module: 'rail'")
    expect(source).not.toContain('cancelRailTransitTask')
    expect(source).toContain('生成分析报告')
    expect(source).toContain('导出链路明细')
    expect(source).toContain('exportMeshLinkDetails')
    expect(source).toContain("router.push('/rail-transit/train-online')")
    expect(source).not.toContain("router.push('/ac-management/mesh-links')")
    expect(source).not.toMatch(/READ ONLY|只读|迁移/)
    expect(source).toContain('删除分析报告')
  })

  it('keeps raw tail collapsed behind an explicit action and stops polling on unmount', () => {
    expect(source).toContain('tail_available')
    expect(source).toContain('loadRawTail')
    expect(source).toContain('onBeforeUnmount')
    expect(source).toContain('clearTimeout')
    expect(source).toContain("document.visibilityState === 'visible'")
    expect(source).toContain('failureCount >= 3 ? 90_000 : 30_000')
    expect(source).not.toContain('setInterval')
    expect(source).not.toContain('absolute_path')
  })

  it('uses the unified platform download instead of navigating the renderer', () => {
    expect(source).toContain('meshArtifactDownloadRequest')
    expect(source).toContain('downloadBackendResource')
    expect(source).not.toContain('meshArtifactDownloadUrl')
    expect(source).not.toContain(':href=')
    expect(meshArtifactDownloadRequest('会话/1', '报告/1', 'mesh.zip')).toEqual({
      apiPath: '/api/rail-transit/mesh-analysis/sessions/%E4%BC%9A%E8%AF%9D%2F1/artifacts/%E6%8A%A5%E5%91%8A%2F1/download',
      suggestedName: 'mesh.zip',
    })
  })

  it('uses typed shared tables with stable identities and scoped detail preferences', () => {
    expect(source).toContain("import NcDataTable from '../../components/table/NcDataTable.vue'")
    expect(source).toContain('NcTableColumn<MeshAnalysisSession>[]')
    expect(source).toContain('NcTableColumn<MeshLinkDetail>[]')
    expect(source).toContain('NcTableColumn<MeshActiveBuildOrder>[]')
    expect(source).not.toContain('NcTableColumn<MeshAnomaly>[]')
    expect(source).not.toContain('<el-table')
    expect(source).not.toContain('<el-table-column')
    expect(source).not.toContain('preference-scope')
    expect(source).toContain('mesh-analysis-active-build-order:v2')
    expect(source).toContain('mesh-analysis-link-details:v3')
    expect(source).toContain('mesh-analysis-switch-events:v3')
    expect(source).not.toContain('AP 统计')
    expect(source).not.toContain('listMeshApStatistics')
    expect(source).toContain('打开任务中心')
    expect(source).toContain("alignmentReason: 'long-text'")
    expect(source).toContain("alignmentReason: 'path'")

    const tableIds = [...source.matchAll(/table-id="([^"]+)"/g)].map((match) => match[1])
    expect(tableIds.length).toBeGreaterThanOrEqual(6)
    expect(new Set(tableIds).size).toBe(tableIds.length)
  })
})
