import { describe, expect, it } from 'vitest'

import source from './RailTransitBaseDataView.vue?raw'

describe('Rail Transit base data maintenance view', () => {
  it('fills the available route width and height while keeping tab content scrollable', () => {
    expect(source).toContain('.rail-base-data { display: flex; width: 100%; height: 100%; max-width: none;')
    expect(source).toContain('.content-card { display: flex; min-width: 0; min-height: 0; flex: 1;')
    expect(source).toContain('.content-card > :deep(.el-tabs) { display: flex; min-width: 0; min-height: 0; flex: 1;')
    expect(source).toContain('.content-card > :deep(.el-tabs > .el-tabs__content) { min-width: 0; min-height: 0; flex: 1; overflow: hidden; }')
    expect(source).toContain('.content-card > :deep(.el-tabs > .el-tabs__content > .el-tab-pane) { width: 100%; height: 100%; overflow: auto; }')
    expect(source).not.toContain('max-width: 1760px')
  })

  it('provides one unified draft workspace with guarded import workflow', () => {
    expect(source).toContain('基础资料总览')
    expect(source).toContain('站点与区间')
    expect(source).toContain('轨旁 AP')
    expect(source).toContain('轨旁 AP 导入预览')
    expect(source).toContain('exportTracksideApBase')
    expect(source).toContain('useTaskStore')
    expect(source).toContain('taskStore.refresh()')
    expect(source).toContain('handleTracksideApFile')
    expect(source).toContain('导入 {{ previewImportableCount }} 条有效数据到草稿')
    expect(source).toContain('@click="saveAllChanges()">保存</el-button>')
    expect(source).toContain('未匹配 FIT-AP')
    expect(source).toContain('TracksideApPlanningTab')
    expect(source).toContain('列车与车载 MR')
    expect(source).toContain('数据质量问题')
    expect(source).toContain('关联运行状态')
    expect(source).toContain('线路与方向参数')
    expect(source).toContain('站序递增时的行驶头端')
    expect(source).toContain('物理安装位置')
    expect(source).toContain('MR 端位代码')
    expect(source).toContain('设备管理 · 站点字段')
    expect(source).toContain('从设备管理生成')
    expect(source).toContain('下载模板')
    expect(source).toContain('导入模板')
    expect(source).toContain('导出当前')
    expect(source).toContain('导出重命名命令')
    expect(source).toContain("row.runtime.fit_ap_name || row.name || row.point_code || '--'")
    expect(source).toContain('ap.runtime.fit_ap_ac_id || undefined')
    expect(source).toContain('ap.runtime.fit_ap_id')
    expect(source).not.toContain('openApMesh')
    expect(source).not.toContain("key: 'line_side', label: '线路方向'")
    expect(source).toContain('递增方向线路侧')
    expect(source).toContain('递减方向线路侧')
    expect(source).toContain('handleApSectionChange(row, String($event))')
    expect(source).toContain("key: 'lldp_suggested_station_id', label: 'LLDP 建议站点'")
    expect(source).toContain('applyLldpStationSuggestion(row)')
    expect(source).toContain('应用到草稿')
    expect(source).toContain('保存后才会写入数据库')
    expect(source).not.toContain("key: 'mesh_related_name', label: '关联 MR'")
    expect(source).toContain('新增节点')
    expect(source).toContain('终点属性')
    expect(source).toContain('线路端点：轨道线路实际到这里结束')
    expect(source).toContain('运营终到/折返')
    expect(source).toContain('运营终到/折返：正常运营列车会在这里作为终到、始发或折返站')
    expect(source).toContain('轨道设施')
    expect(source).toContain('v-model="row.track_facilities" multiple clearable')
    expect(source).toContain('中心里程')
    expect(source).toContain('根据站点生成区间')
    expect(source).toContain('恢复自动值')
    expect(source).toContain("markSectionField(row, 'name')")
    expect(source).not.toContain("canEditRow('section', row.id) && !row.auto_generated")
    expect(source).toContain(':label="option.display_label" :value="option.uid"')
    expect(source).toContain("row.start_station = selected?.persisted_name || value")
    expect(source).toContain("row.result === 'CONFLICT'")
    expect(source).toContain('selected_by_default')
    expect(source).not.toContain('>线路</el-checkbox>')
    expect(source).not.toContain('>运营</el-checkbox>')
    expect(source).toContain('设备管理站点来源预览')
    expect(source).toContain('基础资料模板导入预览')
    expect(source).toContain('应用到当前草稿')
    expect(source).toContain('设备名称、系统名和地址不参与站点识别')
    expect(source).toContain('逐行校验并导入有效数据')
    expect(source).toContain("type BaseDataEditState = 'CLEAN' | 'DIRTY' | 'VALIDATING' | 'SAVING' | 'SAVE_FAILED' | 'READ_ONLY'")
    expect(source).toContain('serverSnapshot')
    expect(source).toContain('editingDraft')
    expect(source).toContain(':data="stationRows"')
    expect(source).toContain(':data="sectionRows"')
    expect(source).toContain(':data="apRows"')
    expect(source).toContain(':data="mrRows"')
    expect(source).toContain('planningDirty')
    expect(source).toContain('editingDraft.value?.tracksideApPlans')
    expect(source).toContain(':model-value="planningRows"')
    expect(source).toContain('@update:model-value="handlePlanningChange"')
    expect(source).not.toContain('保存并锁定')
    expect(source).not.toContain('解锁')
    expect(source).toContain('store.validateChanges(changes)')
    expect(source).toContain('store.saveChanges(changes)')
    expect(source).toContain('store.refreshStationSourcePreview()')
    expect(source).toContain('store.previewStationTemplateFile(file)')
    expect(source).toContain('setFieldErrors(changes, validation.issues)')
    expect(source).toContain('取消修改')
    expect(source).toContain('待删除')
    expect(source).toContain("undoDelete('station', row)")
    expect(source).toContain('onBeforeRouteLeave(async () => !dirty.value || confirmUnsavedChanges())')
    expect(source).not.toContain('sqlite3')
    expect(source).not.toContain('deviceManagement')
    expect(source).toContain('只看阻断问题')
    expect(source).toContain('待人工确认')
    expect(source).toContain('CREATE')
    expect(source).toContain('CONFLICT')
    expect(source).toContain('字段差异')
    expect(source).toContain('逐行校验并导入有效数据')
    expect(source).toContain('previewImportableCount <= 0')
    expect(source).not.toContain('我已核对差异、冲突和目标局点')
    expect(source).toContain('仅显示冲突')
    expect(source).toContain('仅显示无效')
    expect(source).toContain('导出问题明细')
    expect(source).toContain('不影响基础资料导入及 MR 日志识别')
    expect(source).toContain('导入审计')
    expect(source).toContain('回滚')
    expect(source).toContain('<el-pagination')
    expect(source).toContain('handleVisibility')
    expect(source).toContain('store.stopPolling()')
    expect(source).toContain('onBeforeRouteLeave')
    expect(source).toContain("window.addEventListener('beforeunload'")
    expect(source).toContain("route.query.tab")
    expect(source).toContain("name=\"trackside-ap-planning\"")
    expect(source).toContain("path: '/rail-transit/train-online'")
    expect(source).not.toContain("path: '/ac-management/mesh-links'")
    expect(source).not.toContain('getTracksideApTask')
    expect(source).not.toContain('recoverTracksideApTasks')
    expect(source).not.toContain('netconsole.trackside-ap-base.last-task')
    expect(source).not.toContain('打开任务中心')
  })

  it('does not expose credentials, lock mode or unguarded persistence', () => {
    expect(source).toContain("deleteEntity('trackside_ap', row)")
    expect(source).not.toContain('v-if="!locked"')
    expect(source).not.toContain('locked.value')
    expect(source).toMatch(/store\.importPolicies\?\.rollback_enabled/)
    expect(source).not.toContain('密码')
    expect(source).not.toContain('username')
    expect(source).not.toContain('client_count')
  })

  it('owns one editable lifecycle, one save call and one whole-page cancel baseline', () => {
    expect(source).toContain("editState.value = 'CLEAN'")
    expect(source).toContain("if (!store.editSession || saving.value || !dirty.value) return !dirty.value")
    expect(source.match(/store\.saveChanges\(changes\)/g)).toHaveLength(1)
    expect(source).toContain('editingDraft.value = serverSnapshot.value ? cloneDto(serverSnapshot.value) : null')
    expect(source).toContain('当前环境只读：${writeDeniedReason')
    expect(source).toContain('onBeforeRouteLeave(async () => !dirty.value || confirmUnsavedChanges())')
    expect(source).not.toContain('reloadPlan')
    expect(source).not.toContain('watch(activeTab')
  })

  it('uses the shared typed data table contract for every base-data table', () => {
    expect(source).toContain("import NcDataTable from '../../components/table/NcDataTable.vue'")
    expect(source).toContain('NcTableColumn<Station>[]')
    expect(source).toContain('NcTableColumn<DataQualityIssue>[]')
    expect(source).toContain('NcTableColumn<MergeFieldDiff>[]')
    expect(source).not.toContain('<el-table')
    expect(source).not.toContain('<el-table-column')
    expect(source).toContain('#cell-expand')
    expect(source).toContain(':preference-scope="row.entity_id"')
    expect(source).toContain(':preference-scope="String(row.row_number)"')
    expect(source).toContain("alignmentReason: 'long-text'")
    expect(source).toContain("alignmentReason: 'path'")

    const tableIds = [...source.matchAll(/table-id="([^"]+)"/g)].map((match) => match[1])
    expect(tableIds.length).toBeGreaterThanOrEqual(10)
    expect(new Set(tableIds).size).toBe(tableIds.length)
  })
})
