const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let targets=[];
const token=()=>sessionStorage.getItem('agentToken')||'';
async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers['X-Agent-Token']=token();if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const response=await fetch('/api/v1/'+path,{...options,headers});const value=await response.json().catch(()=>({ok:false,error:{message:'响应不是有效 JSON'}}));if(!response.ok||!value.ok){const detail=[value.error?.message,value.error?.hint,value.error?.path].filter(Boolean).join('\n');throw new Error(detail||`HTTP ${response.status}`)}return value.data}
function notice(message,error=false){const n=$('#notice');n.textContent=message;n.className=error?'error':'';n.style.display='block';clearTimeout(n.timer);n.timer=setTimeout(()=>n.style.display='none',5000)}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formObject(form){return Object.fromEntries(new FormData(form).entries())}
function num(v){return Number(v)||0}
async function loadStatus(){const s=await api('status');const labels={agent_name:'Agent',version:'版本',os:'系统',arch:'架构',listen:'监听',uptime:'运行时间',current_tasks:'运行任务',task_count:'任务总数',package_count:'采集包'};$('#status-cards').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="card"><b>${l}</b>${esc(s[k])}</div>`).join('')}
async function loadTools(){const data=await api('tools/status'),labels={iperf3:'iperf3',fping:'fping'};$('#tools-cards').innerHTML=Object.entries(labels).map(([key,label])=>{const t=data.tools[key],state=t.ready?'已找到':t.exists?'DLL 缺失':'未找到',klass=t.ready?'tool-ok':t.exists?'tool-warning':'tool-missing',missing=(t.required_files||[]).filter(x=>!x.exists).map(x=>x.name).join(', ');return `<div class="card tool-card ${klass}"><b>${label}：${state}</b><div class="tool-path">${esc(t.path)}</div>${t.version?`<div>${esc(t.version)}</div>`:''}${missing?`<div>缺失：${esc(missing)}</div>`:''}</div>`}).join('');return data.tools}
async function loadTargets(){const data=await api('targets');targets=data.targets;$('#targets-body').innerHTML=targets.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.name)}</td><td>${esc(t.type)}</td><td>${esc(t.host)}:${esc(t.port)}</td><td>${esc(t.protocol)}</td><td>${esc(t.remark)}</td><td><button data-edit-target="${esc(t.id)}">编辑</button> <button data-test-target="${esc(t.id)}">测试</button> <button data-delete-target="${esc(t.id)}">删除</button></td></tr>`).join('');$('#mr-targets').innerHTML=targets.filter(t=>t.type==='mr').map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${esc(t.host)})</option>`).join('')}
async function loadTasks(){const items=await api('tasks');$('#tasks-body').innerHTML=items.map(t=>`<tr><td>${esc(t.task_id)}</td><td>${esc(t.task_type)}</td><td>${esc(t.status)}</td><td>${esc(t.start_time)}</td><td>${esc(t.end_time)}</td><td>${t.package_download_url?'有':'-'}</td><td><button data-log-task="${esc(t.task_id)}">日志</button> ${['running','stopping'].includes(t.status)?`<button data-stop-task="${esc(t.task_id)}">停止</button>`:''}</td></tr>`).join('')}
async function loadPackages(){const items=await api('packages');$('#packages-body').innerHTML=items.map(p=>`<tr><td>${esc(p.package_id)}</td><td>${esc(p.task_type)}</td><td>${esc(p.end_time)}</td><td>${(p.size/1024).toFixed(1)} KiB</td><td><button data-download-package="${esc(p.package_id)}">下载</button> <button data-delete-package="${esc(p.package_id)}">删除</button></td></tr>`).join('')}
async function refresh(name){try{if(name==='status')await Promise.all([loadStatus(),loadTools()]);if(name==='targets')await loadTargets();if(name==='tasks')await loadTasks();if(name==='packages')await loadPackages()}catch(e){notice(e.message,true)}}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));$$('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#page-'+b.dataset.page).classList.add('active');refresh(b.dataset.page)});
$$('[data-refresh]').forEach(b=>b.onclick=()=>refresh(b.dataset.refresh));
$('#save-token').onclick=()=>{sessionStorage.setItem('agentToken',$('#token').value);notice('Token 已保存到当前浏览器会话');refresh('status')};$('#token').value=token();
$('#target-form').onsubmit=async e=>{e.preventDefault();const v=formObject(e.target),editing=e.target.dataset.editing;v.port=num(v.port);try{await api('targets'+(editing?'/'+encodeURIComponent(editing):''),{method:editing?'PUT':'POST',body:JSON.stringify(v)});notice('目标已保存');e.target.reset();delete e.target.dataset.editing;await loadTargets()}catch(err){notice(err.message,true)}};
$('#target-reset').onclick=()=>{$('#target-form').reset();delete $('#target-form').dataset.editing};
$('#target-import').onchange=async e=>{try{const doc=JSON.parse(await e.target.files[0].text());await api('targets/import',{method:'POST',body:JSON.stringify(doc)});notice('目标已导入');await loadTargets()}catch(err){notice(err.message,true)}e.target.value=''};
$('#target-export').onclick=async()=>{try{const data=await api('targets');downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'targets.json')}catch(e){notice(e.message,true)}};
$('#targets-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.editTarget){const t=targets.find(x=>x.id===b.dataset.editTarget),f=$('#target-form');Object.entries(t).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});f.dataset.editing=t.id;notice('已载入目标，修改后保存')}if(b.dataset.testTarget){await api(`targets/${encodeURIComponent(b.dataset.testTarget)}/test`,{method:'POST'});notice('连接测试成功')}if(b.dataset.deleteTarget&&confirm('确认删除该目标？')){await api(`targets/${encodeURIComponent(b.dataset.deleteTarget)}`,{method:'DELETE'});await loadTargets();notice('目标已删除')}}catch(err){notice(err.message,true)}};
$('#iperf-server-form').onsubmit=e=>start(e,'iperf/server/start',v=>({bind:v.bind,port:num(v.port),protocol:'tcp',extra_args:[]}),true);
$('#iperf-client-form').onsubmit=e=>start(e,'iperf/client/start',v=>({server_host:v.server_host,server_port:num(v.server_port),protocol:v.protocol,duration_sec:num(v.duration_sec),parallel:num(v.parallel),bandwidth_mbps:num(v.bandwidth_mbps),reverse:v.reverse==='on',threshold_mbps:num(v.threshold_mbps),extra_args:[]}),true);
$('#ping-form').onsubmit=e=>start(e,'ping-probe/start',v=>({targets:v.targets.split(/[\s,，]+/).filter(Boolean),tcp_port:num(v.tcp_port),interval_ms:num(v.interval_ms),timeout_ms:num(v.timeout_ms),packet_size:num(v.packet_size),count:num(v.count)}));
$('#mr-form').onsubmit=e=>start(e,'mr/collect/start',v=>({target_id:v.target_id,interval_sec:num(v.interval_sec),items:{terminal_monitor:v.terminal_monitor==='on',channel_busy:v.channel_busy==='on',ap_radio_statistics:v.ap_radio_statistics==='on',wireless_rssi:v.wireless_rssi==='on',wireless_status:v.wireless_status==='on'},auto_package_on_stop:true}));
async function start(e,path,build,checkIperf=false){e.preventDefault();try{if(checkIperf){const tools=await loadTools();if(!tools.iperf3.ready)throw new Error((tools.iperf3.warning||'iperf3 不可用')+'\n请将 iperf3.exe 及相关 DLL 放到 agent/tools/windows-x64/iperf3/')}const task=await api(path,{method:'POST',body:JSON.stringify(build(formObject(e.target)))});notice('任务已启动：'+task.task_id);await loadTasks()}catch(err){notice(err.message,true)}}
$$('[data-stop-type]').forEach(b=>b.onclick=async()=>{try{await api(b.dataset.stopType+'/stop',{method:'POST'});notice('已请求停止')}catch(e){notice(e.message,true)}});
$('#tasks-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.logTask){const data=await api(`tasks/${encodeURIComponent(b.dataset.logTask)}/logs?tail=200`);$('#task-log').textContent=data.lines.join('\n')}if(b.dataset.stopTask){await api(`tasks/${encodeURIComponent(b.dataset.stopTask)}/stop`,{method:'POST'});notice('已请求停止');await loadTasks()}}catch(err){notice(err.message,true)}};
$('#packages-body').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.downloadPackage){const response=await fetch(`/api/v1/packages/${encodeURIComponent(b.dataset.downloadPackage)}/download`,{headers:token()?{'X-Agent-Token':token()}:{}});if(!response.ok)throw new Error('下载失败');downloadBlob(await response.blob(),b.dataset.downloadPackage+'.zip')}if(b.dataset.deletePackage&&confirm('确认删除该采集包？')){await api(`packages/${encodeURIComponent(b.dataset.deletePackage)}`,{method:'DELETE'});await loadPackages();notice('采集包已删除')}}catch(err){notice(err.message,true)}};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
Promise.all([refresh('status'),refresh('targets')]);setInterval(()=>{if($('#page-status').classList.contains('active'))refresh('status')},5000);
